### ISSUE TITLE
Recoverable fatal errorRecoverable fatal error

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/imce#1]
If try to create thumbnails I get :
<code>Recoverable fatal error: Argument 1 passed to file_validate_name_length() must be an instance of File, instance of stdClass given, called in /home/www/backdrop/modules/imce-1.x-1.x/inc/imce.page.inc on line 508 and defined in file_validate_name_length() (line 1659 of /home/www/backdrop/core/includes/file.inc).</code>

**Comment by docwilmot** [comment]
Sorry about that, thought I'd checked everything. Files were converted to classed entities, so needed to change one line. Please advise if all works now.
Thanks

**Comment by sirkitree** [comment]
I've seen this a couple of other places as well. It would be helpful to know how you resolve this one @docwilmot

**Comment by docwilmot** [comment]
@sirkitree it was a one-liner this time; Line 492 in inc/imce.page.inc (directory name also changed to includes/imce.page.inc to follow Backdrop naming convention):
`$file = new stdClass();`
was changed to:
`$file = entity_create('file', array());`
There is a brief change notice here https://api.backdropcms.org/node/26881.

**Comment by sirkitree** [comment]
:+1: Thanks doc!

**Comment by vtad** [comment]
Works for me, closing
