### ISSUE TITLE
Deleting an image does not work and generates following errors

### ISSUE THREAD

**Issue by vtad** [backdrop-contrib/imce#2]
first
Warning: array_flip(): Can only flip STRING and INTEGER values! in DefaultEntityController->load() (line 181 of /home/www/backdrop/core/modules/entity/entity.controller.inc).
second
Recoverable fatal error: Object of class File could not be converted to string in DatabaseStatementBase->execute() (line 2169 of /home/www/backdrop/core/includes/database/database.inc).

**Comment by vtad** [comment]
It works now!

**Comment by docwilmot** [comment]
Updated. I really shouldnt rush testing.
