### ISSUE TITLE
Cross port Issue 1673764 by DamienMcKenna, paulocs, thalles: 508 Keyboard Accessibility 

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/imce#22]
Commit: https://git.drupalcode.org/project/imce/-/commit/ef11aed3bad7801e5d36665dc923ef9a5342c5f0

There was another commit involved, but reverted. We need to double-check, we have everything we need.

Drupal issue: https://www.drupal.org/project/imce/issues/1673764

> ... improve the keyboard accessibility to meet 508 requirements.
Specifically, now the user can tab through and select the file filters, and tab through the list of files and select a file with the enter key.

**Comment by indigoxela** [comment]
To test keyboard navigation, you can use CKEditor 5 or the TinyMCE IMCE plugin. Both seem to work.

With CKE5 open IMCE from within the image dialog. With Tiny IMCE opens directly via the plugin's toolbar item.

**Comment by argiepiano** [comment]
Reviewed and tested. Looks great! Thanks, @indigoxela. Merging on behalf of the @backdrop-contrib/bug-squad
