### ISSUE TITLE
Cross port Issue 2696609 by a.mamallan: Replaced basename() with drupal_basename() for unicode support

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/imce#23]
Commit: https://git.drupalcode.org/project/imce/-/commit/0b60beb560e986ff6b03ebea64db072bb6ff6ae2

Drupal issue: https://www.drupal.org/project/imce/issues/2696609

> ... After upload has been finished, file name was shown wrongly to us only with extension. If same named file is already there then the rename characters is shown accompanied with extension.

"backdrop_basename", of course :wink:

**Comment by indigoxela** [comment]
Testing might be a bit tricky, as transliteration can get into the way here.

It might even be, that this change isn't necessary at all in Backdrop. But hey, it's a small change.

**Comment by argiepiano** [comment]
@indigoxela thanks for this PR. Should `basename()` also be replaced in `imce_file_download()`?

**Comment by indigoxela** [comment]
> Should basename() also be replaced in imce_file_download()?

Good question. This PR conflicts now, anyway, so let's try things out with a fresh one.

**Comment by indigoxela** [comment]
It's a little tricky to test, as Backdrop has transliteration in core, anyway.

**Comment by argiepiano** [comment]
Thanks @indigoxela. This looks good to me. Merging.
