### ISSUE TITLE
Cross port Issue 126679 by emmonsaz, thalles, alimc29, joelpittet, hanief84, ufku, dalin: Bulk Upload Ability 

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/imce#24]
Commit: https://git.drupalcode.org/project/imce/-/commit/d4ab9f14cb4eb82ceacaf6f23a1a0c79f4a6cc62

Drupal issue: https://www.drupal.org/project/imce/issues/126679

> ... It's kinda slow or tiresome when I want to upload a lot of images. So I gues it will be a good idea to have a Bulk Upload Ability in IMCE module

Not sure, yet, if this relies on any previous changes, but it seems worth a try - bulk upload, yay. The initial issue was opened for Drupal 5/6 :grin:

**Comment by indigoxela** [comment]
<s>Yes, in fact this change relies on a previous addition</s> (`IMCE_RENAME_REPLACE => t('Let the user decide which option to choose')`. That's a constant we don't have (yet). But we can just drop that check and functionality in imce_upload_submit() for now. EDIT, nope, the constant actually came after that change...

This also slightly overlaps with #23, as we fiddle in the same function. :shrug:

**Comment by indigoxela** [comment]
With this PR you can select multiple files at once for an upload in IMCE. :tada:

**Comment by argiepiano** [comment]
Reviewed and tested - LGTM. Merging on behalf of the @backdrop-contrib/bug-squad
