### ISSUE TITLE
Broken with Backdrop 1.2.0

### ISSUE THREAD

**Issue by jdanthinne** [backdrop-contrib/imce#6]
CKEditor in Core is great news, but unfortunately, IMCE doesn't work anymore… The new CKEditor allows direct image uploads, but not browsing, which IMCE does perfectly.

**Comment by ghost** [comment]
Made a form alter to backdropimage dialog, to bring back the "Browse server" button.
Note that I choose to make images referenced as "External", to avoid conflicts about file usage...

**Comment by docwilmot** [comment]
Fixed hopefully
